### ISSUE TITLE
how to reconstruction after optimization and PGO.

### ISSUE THREAD

**Issue by minho3** [engcang/FAST-LIO-SAM#1]
I am test your code, and result is good.
so i want reconstruction this.
This code publish keyframes after optimization, but keyframe to keyframe distance are about 1m.
so i want every pose versus 1 lidar frame. how to this implementation?

**Comment by engcang** [comment]
Hi @minho3 . 
The code is already publishing the realtime pose in "pose_stamped" topic.
You can refer this line: https://github.com/engcang/FAST-LIO-SAM/blob/master/fast_lio_sam/src/callbacks.cpp#L31

**Comment by engcang** [comment]
If you don't have further questions regarding the issue, let me close this. @minho3
