### ISSUE TITLE
Questions about bulild 

### ISSUE THREAD

**Issue by wangchuanhao1231** [engcang/FAST-LIO-SAM#6]
Thanks for creating this great resource. 
 I have a question regarding build: the following error is displayed

CMake Error at /home/wang/ws_fast_lio_sam/src/FAST-LIO-SAM/fast_lio_sam/CMakeLists.txt:60 (add_executable):
  Target "fast_lio_sam_node" links to target "Boost::timer" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at /home/wang/ws_fast_lio_sam/src/FAST-LIO-SAM/fast_lio_sam/CMakeLists.txt:55 (add_library):
  Target "fast_lio_sam_methods" links to target "Boost::timer" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at /home/wang/ws_fast_lio_sam/src/FAST-LIO-SAM/fast_lio_sam/CMakeLists.txt:53 (add_library):
  Target "fast_lio_sam_constructor" links to target "Boost::timer" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at /home/wang/ws_fast_lio_sam/src/FAST-LIO-SAM/fast_lio_sam/CMakeLists.txt:57 (add_library):
  Target "fast_lio_sam_callbacks" links to target "Boost::timer" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

How can I solve these problems？

**Comment by engcang** [comment]
Sorry for the late and glad to see that you solved the problem from your end :)

**Comment by wangchuanhao1231** [comment]
> 很抱歉迟到了，很高兴看到您从最终解决了问题:)

Thank you for opening the algorithm. I would like to ask you, what do the two rviz interfaces open at the same time mean respectively

**Comment by engcang** [comment]
Hi @wangchuanhao1231 
The one is representing the result from FAST-LIO and the another one is representing the result from FAST-LIO-SAM, which includes loop-closing and Pose Graph Optimization to correct the drift.

**Comment by wangchuanhao1231** [comment]
> 嗨，一个代表 FAST-LIO 的结果，另一个代表 FAST-LIO-SAM 的结果，其中包括闭环和姿态图优化来纠正漂移。



> Hi @wangchuanhao1231 The one is representing the result from FAST-LIO and the another one is representing the result from FAST-LIO-SAM, which includes loop-closing and Pose Graph Optimization to correct the drift.
Thank you for your reply
